### ISSUE TITLE
Not adding time correctly

### ISSUE THREAD

**Issue by JeremyKnudsen** [melvitax/AFDateHelper#10]
I liked these extensions but there is one fairly major issue. I believe this is what is referenced in one of the other listed issues.

When adding time to a specific date, you should be using the `dateByAddingComponents:toDate:options:` function on the `NSCalendar` class. Otherwise, by just adding seconds it will not function properly across changes in daylight savings, leap years, and potentially other scenarios.

This should be used in all your `dateByAdding...` functions.

For example, below is the proper way to add one day to the current date in Objective-C.

```objective-c
+ (NSDate *)addDays:(NSInteger)days ToDate:(NSDate *)date
{
    NSCalendar *currentCalendar = [[NSCalendar alloc] initWithCalendarIdentifier:NSCalendarIdentifierGregorian];
    
    NSDateComponents *dateComponents = [[NSDateComponents alloc] init];
    dateComponents.day = days;
    
    return [currentCalendar dateByAddingComponents:dateComponents toDate:date options:0];
}
```

Hope this is clear.

**Comment by melvitax** [comment]
Thanks, fixed in https://github.com/melvitax/AFDateHelper/commit/15daf87d143c927ec0c118504afb499e69abd84e
