### ISSUE TITLE
ISO8601 format currently doesn't work with milliseconds

### ISSUE THREAD

**Issue by scottymac** [melvitax/AFDateHelper#13]
Just a heads up that ISO8601 formatted dates with milliseconds aren't currently supported. Pretty easy to add:
```
let ISO8601Format = "yyyy-MM-dd'T'HH:mm:ssZ"
let ISO8601FormatWithMilliseconds = "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
```
Easy enough to just try the second formatter if the first one fails.

**Comment by melvitax** [comment]
Added feature on latest release
