### ISSUE TITLE
relativeTimeToString() incorrect output

### ISSUE THREAD

**Issue by jamesallison** [melvitax/AFDateHelper#29]
`NSDate().relativeTimeToString()` will return a date, not a relative time measure if the date in question is over 7 days in the past

**Comment by nkanellopoulos** [comment]
Apparently this is by design.
You could tweak the code in AFDateExtension.swif, around line 856:
`if days < 7 {`

**Comment by melvitax** [comment]
This is by design. Similar to how time ago works.
