### ISSUE TITLE
Calculation is not correct

### ISSUE THREAD

**Issue by dwlnetnl** [melvitax/AFDateHelper#3]
The code does calculation with a hard defined day (24 hours). This isn't the correct way to do date and time calculation because there is daylight savings time in some regions.

**Comment by melvitax** [comment]
Would love to get this fixed. Which calculations are you referring to?

**Comment by dwlnetnl** [comment]
I mean the assumption that a day contains always 24 hours. When there is a daylight savings time transition, a day is either 23 or 25 hours long.
See: https://github.com/melvitax/AFDateHelper/blob/master/AFDateHelper/AFDateExtension.swift#L443

Issue #10 is also hinting at this. Date and time calculations aren't simple and easy. There is a whole WWDC session about this specific subject. https://developer.apple.com/videos/wwdc/2013/?id=227

**Comment by melvitax** [comment]
Thanks, fixed in https://github.com/melvitax/AFDateHelper/commit/15daf87d143c927ec0c118504afb499e69abd84e
