### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by hardikdevios** [melvitax/AFDateHelper#35]
Please support this

**Comment by embassem** [comment]
+1

**Comment by damirstuhec** [comment]
+1

**Comment by hardikdevios** [comment]
If any body interested i have done this on my side.

`github "hardikdevios/AFDateHelper"`

Link of this : [https://github.com/hardikdevios/AFDateHelper](url)

**Comment by patricks** [comment]
Now my PR is merged so this repo also has carthage support, the only thing which is missing is tag a new release.

**Comment by melvitax** [comment]
@patricks  Do I need to do anything other than tag a new release in GitHub? Does Carthage require a command line push like Cocoapods?

**Comment by patricks** [comment]
No tag a new release is everything. Btw. maybe you can change the ios deployment target to 9.0 or less. now its 9.3 and thats very high. 😉

**Comment by hardikdevios** [comment]
Well thanks guys i have just put for myself by using fork i have not check the PR lols any way Great to hear that **PR** is merged.

**Comment by melvitax** [comment]
Thanks to @patricks Carthage is now supported.

**Comment by hardikdevios** [comment]
Well i supposed you should keep target from iOS 8. Now unable to use, are you going to put the support from iOS 8 ?
