### ISSUE TITLE
Redundant Info.plist file

### ISSUE THREAD

**Issue by SanjoDeundiak** [melvitax/AFDateHelper#44]
When installing using pods workspace contains redundant Info.plist file in pod root folder. This blocks uploading build to AppStore (while simulator is still able to run app)

**Comment by hardikdevios** [comment]
Just now i have the same problem shocked me also with so many errors during Appstore submission so i have removed the info.plist file which is outside the supporting file and problem solved for now. 
#41 Similer

**Comment by SanjoDeundiak** [comment]
Yes, but this solves problem till next 'pod update', or, if you use build server, you need to add some hooks with workaround, which is not good

**Comment by JustinDMoore** [comment]
Is there an update on this?

**Comment by melvitax** [comment]
Fixed in latest release

**Comment by JustinDMoore** [comment]
Not fixed in 3.4.1.  Found alternative dependency to use instead.

**Comment by melvitax** [comment]
Maybe is a cache thing. The pod spec should include only the files in the AFDateHelper directory, and that directory now only has the 1 file.
