### ISSUE TITLE
Swift3?

### ISSUE THREAD

**Issue by SanjoDeundiak** [melvitax/AFDateHelper#49]
Can we expect swift 3 migration?

**Comment by CalQL8ed-K-OS** [comment]
I've migrated to Swift 3 over [here](https://github.com/CalQL8ed-K-OS/AFDateHelper/tree/swift-3)
No tests though so I'm not sure what the impact is

**Comment by vCrespoP** [comment]
+1

**Comment by CalQL8ed-K-OS** [comment]
Closed by #46
