### ISSUE TITLE
Please add support for Swift 3

### ISSUE THREAD

**Issue by patricks** [melvitax/AFDateHelper#52]
Please add support for swift 3. If I switch to swift 3 I get many compilation errors.

**Comment by vCrespoP** [comment]
+1

**Comment by CalQL8ed-K-OS** [comment]
Should be closed by #46

**Comment by melvitax** [comment]
Fixed in https://github.com/melvitax/AFDateHelper/commit/e17f011824dbe6b7be86e0a2c2e0e50cea36335d
