### ISSUE TITLE
an nsformatter is created for each toString() call

### ISSUE THREAD

**Issue by jlnbuiles** [melvitax/AFDateHelper#9]
by looking at your code, i see that you create a new `NSDateFormatter` every time `toString()` is called on a date object.

`NSDateFormatters` are very expensive to create. see apple's [NSDateFormatter's guide](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/DataFormatting/Articles/dfDateFormatting10_4.html#//apple_ref/doc/uid/TP40002369-SW1) in the section titled `Cache Formatters for Efficiency`.

Hence i think you should create a class-wide instance or a dictionary that associates formatters with keys (if multiple are required).

thanks for the class though! super helpful!

**Comment by melvitax** [comment]
Thanks for the head up, this was on my todo list and it's now implemented.
